### ISSUE TITLE
sposta i cursori remoti quando si clicca su un'altra posizione

### ISSUE THREAD

**Issue by maborghe** [PoliDox/PoliDox#11]
aggiungere un messaggio "cursor" alla message API per notificare che un cursore si è spostato anche senza aggiungere o cancellare caratteri

**Comment by DavideAG** [comment]
Per questo penso ci sia un problema perché @GabrieleMn aveva provato a catturare il tasto sinistro del mouse quando effettuato sul QTextEdit Widget ma non può essere fatto perché questo widget ha già uno slot di gestione del left click di cui non può essere fatto override.

@GabrieleMn confermi?

**Comment by GabrieleMn** [comment]
Avevo creato un eventFilter, mi pare ci sia ancora nel codice ma commentato. Il problema è che QTextEdit ha un campo viewPort che cattura già lui l'evento click sinistro e quindi nonostante si installi un eventFilter al QTextEdit l'evento viene consumato prima.

**Comment by maborghe** [comment]
fatto, se vi serve per altre features potete usare il lamba connesso a QTextEdit::cursorPositionChanged (NON QTextDocument::cursorPositionChanged)
