### ISSUE TITLE
ultima lettera di "online users" e "offline users" nell'editor è troncata

### ISSUE THREAD

**Issue by maborghe** [PoliDox/PoliDox#17]

**Comment by DavideAG** [comment]
Ciao mat, potresti indicare meglio il bug? non riesco a visualizzarlo
![image](https://imgur.com/BN1Dr22.png)

**Comment by maborghe** [comment]
io lo vedo così

![image](https://user-images.githubusercontent.com/26746380/69008591-61ba8680-094c-11ea-9c17-99faf0d06e47.png)

**Comment by DavideAG** [comment]
Hum strano. Possiamo provare ad anteporre il pallino verde/rosso rispetto alla label
