### ISSUE TITLE
tasti di undo e redo non funzionano

### ISSUE THREAD

**Issue by maborghe** [PoliDox/PoliDox#20]

**Comment by DavideAG** [comment]
ho provato a lavorarci ma alla pressione del tasto di undo la contentChange riceve sia un carattere da rimuovere che uno da inserire.
![image](https://imgur.com/oAJb2a0.png)

Ma quando si fa "undo" o "redo" il cursore remoto che fine fa? anche lui si sposta nella posizione precedente?
Comunque i tasti di undo e redo erano funzionanti

**Comment by GabrieleMn** [comment]
non compreso nelle specifiche
