### ISSUE TITLE
se si seleziona una parola per metà in grassetto il grassetto sparisce

### ISSUE THREAD

**Issue by maborghe** [PoliDox/PoliDox#24]
Questo vale per ogni formato di stile (dimensioni, corsivo, etc.)

**Comment by GabrieleMn** [comment]
è un problema che è nato da quando i cursori si spostano ad ogni click del mouse. Se seleziono una parola, si sposta di conseguenza anche il cursore. Siamo sicuri si debba comportare così?
Il cursore dovrebbe restare fisso all'inizio della selezione.
