### ISSUE TITLE
Eccezioni database manager

### ISSUE THREAD

**Issue by GabrieleMn** [PoliDox/PoliDox#32]

**Comment by FedericoVasile1** [comment]
gestione eccezioni effettuata. 
Attualmente, se il server perde la connessione con il database(ad es. nel caso in cui il processo db muoia) il server provvede a chiudersi, dato che l'app non sarà più in grafo di mantenere una stato consistente.
Deve essere mostrato al client un popup che segnala la chiusura del server.
