### ISSUE TITLE
Fare galleggiare Profile su Editor dopo l'update dell'immagine

### ISSUE THREAD

**Issue by DavideAG** [PoliDox/PoliDox#36]
Questo caso si verifica solo su MAC. Lo assegno a @FedericoVasile1 e @GabrieleMn perché siete gli unici a poterlo testare

**Comment by FedericoVasile1** [comment]
eseguito da sminnoz, grazie. aspetto suo conferma per chiuderlo

**Comment by GabrieleMn** [comment]
sminnoz conferma
