### ISSUE TITLE
evita crash del server se arriva immagine vuota

### ISSUE THREAD

**Issue by maborghe** [PoliDox/PoliDox#39]
lo controlliamo lato client ma nel caso non funzionasse qualcosa non va bene che il server crashi, c'è da inserire un controllo del campo json e ritornare fail. Questo vale sia per la registrazione sia per l'image update

**Comment by FedericoVasile1** [comment]
inserito il controllo lato server, se quando il messaggio json arriva al server il campo image è vuoto, la richiesta viene rifiuata. Il server ritorna il messaggio fail.
rimane da gestire il controllo lato client.
