### ISSUE TITLE
quando seleziono il testo di un utente e cancello un carattere in mezzo mi deseleziona anche il carattere a dx

### ISSUE THREAD

**Issue by DavideAG** [PoliDox/PoliDox#9]

**Comment by maborghe** [comment]
![Screenshot from 2019-11-09 14-36-17](https://user-images.githubusercontent.com/26746380/68529408-b3d12b80-02fe-11ea-9916-1117aafcc620.png)
![Screenshot from 2019-11-09 14-36-31](https://user-images.githubusercontent.com/26746380/68529404-ab78f080-02fe-11ea-9ae6-4482fcd1af2f.png)
